# Generated by Django 6.0.6 on 2026-06-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hizmet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('detail', models.TextField()),
                ('price', models.CharField(max_length=100)),
                ('price_note', models.CharField(blank=True, max_length=200)),
                ('features', models.JSONField(default=list)),
                ('gallery', models.JSONField(default=list)),
                ('video', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('detail', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('bg_color', models.CharField(blank=True, max_length=50)),
                ('date', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('features', models.JSONField(default=list)),
                ('gallery', models.JSONField(default=list)),
                ('video', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
