# Generated by Django 6.0.6 on 2026-06-30 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_iletisimmesaji_sitesettings_alter_hizmet_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='detail_block_1_active',
            field=models.BooleanField(default=True, verbose_name='Блок 1 - Активен'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='detail_block_1_label',
            field=models.CharField(default='Срок', max_length=100, verbose_name='Блок 1 - Этикетка'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='detail_block_1_value',
            field=models.CharField(default='3-12 месяцев', max_length=200, verbose_name='Блок 1 - Значение'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='detail_block_2_active',
            field=models.BooleanField(default=True, verbose_name='Блок 2 - Активен'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='detail_block_2_label',
            field=models.CharField(default='Гарантия', max_length=100, verbose_name='Блок 2 - Этикетка'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='detail_block_2_value',
            field=models.CharField(default='2 года', max_length=200, verbose_name='Блок 2 - Значение'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='detail_block_3_active',
            field=models.BooleanField(default=True, verbose_name='Блок 3 - Активен'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='detail_block_3_label',
            field=models.CharField(default='Ключи', max_length=100, verbose_name='Блок 3 - Этикетка'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='detail_block_3_value',
            field=models.CharField(default='Под ключ', max_length=200, verbose_name='Блок 3 - Значение'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='detail_block_4_active',
            field=models.BooleanField(default=True, verbose_name='Блок 4 - Активен'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='detail_block_4_label',
            field=models.CharField(default='Локация', max_length=100, verbose_name='Блок 4 - Этикетка'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='detail_block_4_value',
            field=models.CharField(default='Стамбул и область', max_length=200, verbose_name='Блок 4 - Значение'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='detail_block_5_active',
            field=models.BooleanField(default=False, verbose_name='Блок 5 - Активен'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='detail_block_5_label',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Блок 5 - Этикетка'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='detail_block_5_value',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Блок 5 - Значение'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='detail_block_6_active',
            field=models.BooleanField(default=False, verbose_name='Блок 6 - Активен'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='detail_block_6_label',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Блок 6 - Этикетка'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='detail_block_6_value',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Блок 6 - Значение'),
        ),
    ]
