# Generated by Django 6.0.6 on 2026-06-30 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_detail_block_1_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_stat_1_label',
            field=models.CharField(default='Лет опыта', max_length=100, verbose_name='Stat 1 - Etiket'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_stat_1_number',
            field=models.CharField(default='15', max_length=50, verbose_name='Stat 1 - Sayı'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_stat_2_label',
            field=models.CharField(default='Довольных клиентов', max_length=100, verbose_name='Stat 2 - Etiket'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_stat_2_number',
            field=models.CharField(default='120', max_length=50, verbose_name='Stat 2 - Sayı'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_stat_3_label',
            field=models.CharField(default='Удовлетворённость %', max_length=100, verbose_name='Stat 3 - Etiket'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_stat_3_number',
            field=models.CharField(default='98', max_length=50, verbose_name='Stat 3 - Sayı'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_stats_active',
            field=models.BooleanField(default=True, verbose_name='Hero Stats - Aktif/Pasif'),
        ),
        migrations.AlterField(
            model_name='galeriresim',
            name='hizmet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resimler', to='core.hizmet'),
        ),
        migrations.AlterField(
            model_name='galeriresim',
            name='image',
            field=models.ImageField(upload_to='galeri/%Y/%m/%d/', verbose_name='Resim'),
        ),
        migrations.AlterField(
            model_name='galeriresim',
            name='proje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resimler', to='core.proje'),
        ),
        migrations.AlterField(
            model_name='hizmet',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list, verbose_name='Галерея (устаревший)'),
        ),
        migrations.AlterField(
            model_name='hizmet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hizmetler/kapak/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='hizmet',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videolar/', verbose_name='Видео файл'),
        ),
        migrations.AlterField(
            model_name='proje',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list, verbose_name='Галерея (устаревший)'),
        ),
        migrations.AlterField(
            model_name='proje',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projeler/kapak/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='proje',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videolar/', verbose_name='Видео файл'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_text',
            field=models.TextField(default='С 2008 года мы реализуем проекты в Стамбуле и по всей Турции.', verbose_name='О нас - Текст'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.TextField(default='15-летний опыт в строительстве, ремонте, отделке и дизайне интерьеров.', verbose_name='Hero - Описание'),
        ),
    ]
