# Generated by Django 6.0.6 on 2026-06-30 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_hero_stat_1_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='nav_link_email',
            field=models.CharField(blank=True, default='info@ustainsaat.com', max_length=100, verbose_name='Email Adresi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nav_link_phone',
            field=models.CharField(blank=True, default='05551234567', max_length=50, verbose_name='Telefon Numarası'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nav_link_telegram',
            field=models.CharField(blank=True, default='https://t.me/ustainsaat', max_length=200, verbose_name='Telegram Linki'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nav_link_whatsapp',
            field=models.CharField(blank=True, default='https://wa.me/905551234567', max_length=200, verbose_name='WhatsApp Linki'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_facebook',
            field=models.CharField(blank=True, default='https://facebook.com/ustainsaat', max_length=200, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_instagram',
            field=models.CharField(blank=True, default='https://instagram.com/ustainsaat', max_length=200, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_telegram',
            field=models.CharField(blank=True, default='https://t.me/ustainsaat', max_length=200, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_youtube',
            field=models.CharField(blank=True, default='https://youtube.com/ustainsaat', max_length=200, verbose_name='YouTube'),
        ),
    ]
